# on: push
# jobs:
#   build-node:
#     runs-on: ubuntu-latest
#     container: node:20
#     steps:
#       - run: node --version
#       - run: npm -- version
#       - uses: actions/checkout@v3
#       - run: npm install
#         working-directory: backend
#       - run: npm start
#         working-directory: backend

name: Deploy Backend Service to ECR
on: push
jobs:
  build:
    name: Build Image for backend
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: set NOW env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the app image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.login-ecr.outputs.registry }}/routeme:proj2_backend_${{env.NOW}}
          secrets: |
            "mongo_username = ${{ secrets.MONGO_USERNAME }}"
            "mongo_password = ${{ secrets.MONGO_PASSWORD }}"
            "g_app_cred = ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}"
            "g_maps_api_key = ${{secrets.GOOGLE_MAPS_API_KEY}}"

  # build-frontend:
  #   name: Build Image for frontend
  #   runs-on: ubuntu-latest
  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v3

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1

  #     - name: Login to Amazon ECR
  #       id: login-ecr
  #       uses: aws-actions/amazon-ecr-login@v2
  #     - name: set NOW env variable
  #       run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

  #     - name: Build, tag, and push image to Amazon ECR
  #       env:
  #         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #         ECR_REPOSITORY: routeme
  #         IMAGE_TAG: proj2_frontend_${{env.NOW}}
  #       run: |
  #         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
  #         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  #       working-directory: frontend
